export const ErrorCode = {
    // Auth
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    INVALID_TOKEN: 'INVALID_TOKEN',

    // User
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_ALREADY_INACTIVE: 'USER_ALREADY_INACTIVE',

    // Local
    LOCAL_NOT_FOUND: 'LOCAL_NOT_FOUND',
    LOCAL_ALREADY_EXISTS: 'LOCAL_ALREADY_EXISTS',
    LOCAL_NOT_VERIFIED: 'LOCAL_NOT_VERIFIED',

    // Event
    EVENT_NOT_FOUND: 'EVENT_NOT_FOUND',

    // Category
    CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
    CATEGORY_ALREADY_EXISTS: 'CATEGORY_ALREADY_EXISTS',

    // Favorite
    FAVORITE_ALREADY_EXISTS: 'FAVORITE_ALREADY_EXISTS',
    FAVORITE_NOT_FOUND: 'FAVORITE_NOT_FOUND',

    // Notification
    NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',

    // Comment
    COMMENT_NOT_FOUND: 'COMMENT_NOT_FOUND',

    // Incident
    INCIDENT_NOT_FOUND: 'INCIDENT_NOT_FOUND',

    // Preference
    PREFERENCE_ALREADY_EXISTS: 'PREFERENCE_ALREADY_EXISTS',
    PREFERENCE_NOT_FOUND: 'PREFERENCE_NOT_FOUND',

    // General
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
} as const

export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode]